export const columns = [
  { key: 'index', label: '', defaultVisible: true, sortable: false, auto: true, type: '' },
  { key: 'title', label: 'Client', defaultVisible: true, sortable: true, auto: false, type: '' },
  { key: 'production', label: 'Production', defaultVisible: true, sortable: false, auto: true, type: 'link' },
  { key: 'staging', label: 'Staging', defaultVisible: true, sortable: false, auto: true, type: 'link' },
  { key: 'createdAt', label: 'Date of creation', defaultVisible: false, sortable: true, auto: true, type: 'date' },
  { key: 'lastCommitAt', label: 'Last commit', defaultVisible: false, sortable: true, auto: true, type: 'date' },
  { key: 'productionDate', label: 'Production date', defaultVisible: false, sortable: true, auto: true, type: 'date' },
  { key: 'siteService', label: 'Site/Service', defaultVisible: false, sortable: true, auto: false, type: 'server' },
  { key: 'hosting', label: 'Hosting', defaultVisible: false, sortable: false, auto: false, type: 'server' },
  { key: 'server', label: 'Server', defaultVisible: false, sortable: true, auto: false, type: 'server' },
  { key: 'wpVersion', label: 'WP Version', defaultVisible: true, sortable: true, auto: true, type: 'server' },
  { key: 'cloudflare', label: 'Cloudflare', defaultVisible: true, sortable: true, auto: true, type: 'server' },
  { key: 'ssl', label: 'SSL', defaultVisible: false, sortable: false, auto: true, type: 'server' },
  { key: 'ipRestriction', label: 'IP Restriction', defaultVisible: false, sortable: false, auto: false, type: 'server' },
  { key: 'csp', label: 'CSP', defaultVisible: false, sortable: false, auto: true, type: 'server' },
  { key: 'phpVersion', label: 'PHP version', defaultVisible: false, sortable: true, auto: false, type: 'server' },
  { key: 'framework', label: 'Framework', defaultVisible: false, sortable: false, auto: true, type: 'server' },
  { key: 'twoFa', label: '2FA', defaultVisible: false, sortable: false, auto: true, type: 'feature' },
  { key: 'hiddenLogin', label: 'Hidden login', defaultVisible: false, sortable: false, auto: true, type: 'feature' },
  { key: 'hasSolr', label: 'SOLR', defaultVisible: false, sortable: false, auto: true, type: 'feature' },
  { key: 'pressReleases', label: 'Press releases', defaultVisible: false, sortable: false, auto: true, type: 'external' },
  { key: 'dataProvider', label: 'Share data provider', defaultVisible: false, sortable: true, auto: true, type: 'external' },
  { key: 'hasGoogleAnalytics', label: 'Analytics', defaultVisible: false, sortable: false, auto: true, type: 'external' },
  { key: 'cookieProvider', label: 'Cookie provider', defaultVisible: false, sortable: true, auto: true, type: 'external' },
  { key: 'wcag', label: 'WCAG', defaultVisible: false, sortable: false, auto: false, type: 'test' },
  { key: 'bsScan', label: 'BS Scan', defaultVisible: false, sortable: true, auto: false, type: 'test' },
  { key: 'lastResponsetime', label: 'Response time', defaultVisible: true, sortable: true, auto: true, type: 'test' },
  {
    key: 'cloudflarePercentage',
    label: 'Cloudflare 24hrs bandwidth (GB) / requests',
    defaultVisible: true,
    sortable: true,
    auto: true,
    type: 'test'
  },
]
